# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: SampleApp/BackEnd/Dockerfile
    ports:
      - 8080:8080
